export * from './error';
export * from './excursions';
export * from './home';
export * from './login';
export * from './students';
export * from './user';
export * from './virtual';
export * from './virtual-excursions/grodno';
export { AvgustovskiyKanal } from './virtual-excursions/grodno/avgustovsckiy-kanal';
export { ParkBolteniki } from './virtual-excursions/grodno/park-bolteniki';
export { ParkZhilibera } from './virtual-excursions/grodno/park-zhilibera';
export * from './virtual-excursions/palaces';
export { LidaPalace } from './virtual-excursions/palaces/lida';
export { MirPalace } from './virtual-excursions/palaces/mir';
export { NunhartPalace } from './virtual-excursions/palaces/nunhart';
export * from './virtual-excursions/voronovo/1';
export * from './virtual-excursions/voronovo/2';
export * from './virtual-excursions/voronovo/3';
export * from 'pages/virtual-excursions/voronovo';
